export const NIGERIAN_BANKS = [
  { code: "044", name: "Access Bank" },
  { code: "023", name: "Citibank Nigeria" },
  { code: "063", name: "Diamond Bank" },
  { code: "050", name: "Ecobank Nigeria" },
  { code: "084", name: "Enterprise Bank" },
  { code: "070", name: "Fidelity Bank" },
  { code: "011", name: "First Bank of Nigeria" },
  { code: "214", name: "First City Monument Bank (FCMB)" },
  { code: "058", name: "Guaranty Trust Bank (GTBank)" },
  { code: "030", name: "Heritage Bank" },
  { code: "301", name: "Jaiz Bank" },
  { code: "082", name: "Keystone Bank" },
  { code: "526", name: "Parallex Bank" },
  { code: "076", name: "Polaris Bank" },
  { code: "101", name: "Providus Bank" },
  { code: "221", name: "Stanbic IBTC Bank" },
  { code: "068", name: "Standard Chartered Bank" },
  { code: "232", name: "Sterling Bank" },
  { code: "100", name: "SunTrust Bank" },
  { code: "032", name: "Union Bank of Nigeria" },
  { code: "033", name: "United Bank for Africa (UBA)" },
  { code: "215", name: "Unity Bank" },
  { code: "035", name: "Wema Bank" },
  { code: "057", name: "Zenith Bank" },
  { code: "999", name: "Kuda Bank" },
  { code: "303", name: "OPay" },
  { code: "304", name: "PalmPay" },
  { code: "305", name: "Moniepoint" },
  { code: "306", name: "Carbon" },
  { code: "307", name: "Sparkle" },
  { code: "308", name: "VFD Microfinance Bank" },
  { code: "309", name: "ALAT by Wema" },
  { code: "310", name: "Rubies Bank" },
  { code: "311", name: "Titan Trust Bank" },
  { code: "312", name: "Globus Bank" },
  { code: "313", name: "Premium Trust Bank" },
  { code: "314", name: "Lotus Bank" },
  { code: "315", name: "TAJ Bank" },
  { code: "316", name: "Eyowo" },
  { code: "317", name: "FairMoney" },
  { code: "318", name: "LAPO Microfinance Bank" },
  { code: "319", name: "Mint Finex MFB" },
  { code: "320", name: "Raven Bank" },
  { code: "321", name: "Paga" },
] as const;

export type NigerianBank = typeof NIGERIAN_BANKS[number];
